# Generated by Django 5.0.1 on 2024-01-09 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('gender', models.CharField(max_length=200)),
                ('contact_number', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('emergency_contact', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('medical_condition_description', models.TextField()),
                ('current_medication', models.TextField()),
            ],
        ),
    ]
